### ISSUE TITLE
incorrect font size in a few places

### ISSUE THREAD

**Issue by rystills** [rystills/rock-raiders-remake#13]
A few instances of text are not being rendered at the correct size. This includes the menu options, The "Press Enter to Begin" game start message, and the score screen text. These text instances should be adjusted to render at the correct size, or repositioned to fit on the screen at their new size.

**Comment by Scarabol** [comment]
Pls don't waste time on this one. The menus will be loaded from configuration pretty soon and afterwards we can check again.
