### ISSUE TITLE
Will this game get a 3D mode?

### ISSUE THREAD

**Issue by MartinX3** [rystills/rock-raiders-remake#7]
Thank you for your try to port this wonderful & old game to JS.

Do you plan to integrate a 3D view like in the original game?

**Comment by rystills** [comment]
At the moment there are no plans to introduce 3D rendering I'm afraid. From what I remember the game's models and animations use a very old format, making converting them to something usable with JS a huge hassle. Should these plans change, I will reopen this issue accordingly.
